# Generated by Django 4.1.1 on 2022-10-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bugatti", name="desc", field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="bugatti", name="img", field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="bugatti", name="img1", field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="bugatti", name="img2", field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="bugatti", name="img3", field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="bugatti", name="img4", field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="bugatti", name="img5", field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="bugatti", name="img6", field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="bugatti",
            name="name",
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bugatti",
            name="price",
            field=models.TextField(max_length=100, null=True),
        ),
    ]
