# Generated by Django 4.1.1 on 2022-10-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_bugatti_img5_remove_bugatti_img6"),
    ]

    operations = [
        migrations.CreateModel(
            name="koenigsegg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=100, null=True)),
                ("price", models.TextField(max_length=100, null=True)),
                ("desc", models.TextField(null=True)),
                ("img", models.TextField(null=True)),
                ("img1", models.TextField(null=True)),
                ("img2", models.TextField(null=True)),
                ("img3", models.TextField(null=True)),
                ("img4", models.TextField(null=True)),
            ],
        ),
    ]
